/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 68e2b93ed4242f6de7f871f7.glb --transform
Files: 68e2b93ed4242f6de7f871f7.glb [1.24MB] > /home/thrill/Downloads/68e2b93ed4242f6de7f871f7-transformed.glb [566.26KB] (54%)
*/

import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
import { useGraph } from "@react-three/fiber";
import React, { useEffect, useRef } from "react";
import { SkeletonUtils } from "three-stdlib";

const Developer = ({ animationName = "idle", ...props }) => {
  const groupRef = useRef();
  const { scene } = useGLTF("models/developer.glb");
  const clone = React.useMemo(() => {
    return SkeletonUtils.clone(scene);
  }, [scene]);
  const { nodes, materials } = useGraph(clone);

  const { animations: idleAnimation } = useFBX("/models/human/Idle-dev.fbx");
  const { animations: clappingAnimation } = useFBX(
    "/models/animations/clapping.fbx",
  );
  const { animations: saluteAnimation } = useFBX(
    "/models/animations/salute.fbx",
  );
  const { animations: victoryAnimation } = useFBX(
    "/models/animations/victory.fbx",
  );

  const animations = React.useMemo(() => {
    idleAnimation[0].name = "idle";
    clappingAnimation[0].name = "clapping";
    saluteAnimation[0].name = "salute";
    victoryAnimation[0].name = "victory";
    return [
      idleAnimation[0],
      clappingAnimation[0],
      saluteAnimation[0],
      victoryAnimation[0],
    ];
  }, [idleAnimation, clappingAnimation, saluteAnimation, victoryAnimation]);

  const { actions } = useAnimations(animations, groupRef);
  useEffect(() => {
    if (!actions || !actions[animationName]) return;

    // Stop all other actions
    Object.keys(actions).forEach((key) => {
      if (key !== animationName && actions[key].isRunning()) {
        actions[key].fadeOut(0.2);
      }
    });

    // Play the new animation
    actions[animationName].reset().fadeIn(0.2).play();

    return () => {
      if (actions[animationName]) {
        actions[animationName].fadeOut(0.2).reset();
      }
    };
  }, [animationName, actions]);
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Glasses.geometry}
        material={materials.Wolf3D_Glasses}
        skeleton={nodes.Wolf3D_Glasses.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
    </group>
  );
};

useGLTF.preload("models/developer.glb");
export default Developer;
